image: mrcaidev/telemedicine-smart-assistant
host: localhost
port: 80
livenessProbe: /livez
readinessProbe: /readyz
paths:
  - /sessions
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
minReplicas: 1
maxReplicas: 1
kafkaCertsNeeded: false
secrets:
  AGENT_ENDPOINT: https://rple22irdjo2o7ujic6jsgqy.agents.do-ai.run/api/v1/
  AGENT_ACCESS_KEY: KkkSNvyp5VGydbd4u8kWS6a6BeaInBI_
  MONGO_URL: mongodb://dev:dev@smart-assistant-mongo-mongodb:27017/?authSource=smart_assistant
  REDIS_URL: redis://default:dev@smart-assistant-redis-master:6379
