image: mrcaidev/telemedicine-smart-assistant
port: 80
livenessProbe: /livez
readinessProbe: /readyz
paths:
  - /sessions
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
