ingressRoute:
  dashboard:
    enabled: true

extraObjects:
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: circuit-breaker
    spec:
      circuitBreaker:
        expression: NetworkErrorRatio() > 0.3

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: content-type
    spec:
      contentType: {}

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: forward-auth
    spec:
      forwardAuth:
        address: http://auth:3000/gateway
        authResponseHeadersRegex: ^X-User-

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: headers
    spec:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders:
          - Authorization
        accessControlAllowMethods:
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        accessControlAllowOriginListRegex:
          - ^https?:\\/\\/(.+\\.)?localhost(:[0-9]+)?$
          - ^https?:\\/\\/(.+\\.)?telemedicine\\.ink$

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: rate-limit
    spec:
      rateLimit:
        average: 100
        burst: 200
