image: mrcaidev/telemedicine-notification
host: localhost
port: 3000
livenessProbe: /livez
readinessProbe: /readyz
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
minReplicas: 1
maxReplicas: 1
kafkaCertsNeeded: false
