import Navbar from "@/components/nav/Navbar";
import DoctorSidebar from "@/components/nav/DoctorSidebar";
import type { Metadata } from "next";
import ProtectedRoute from "@/components/auth/protected-route";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <ProtectedRoute>
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <div className="flex flex-1">
            <div className="w-56 shrink-0 h-screen sticky top-0">
              <DoctorSidebar />
            </div>
            <main className="flex-1 p-6 bg-gray-50 overflow-y-auto">{children}</main>
          </div>
        </div>
      </ProtectedRoute>
    </>
  );
}
