image: mrcaidev/telemedicine-appointment
host: localhost
port: 3000
livenessProbe: /livez
readinessProbe: /readyz
paths:
  - /appointments
  - /doctor-availabilities
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
minReplicas: 1
maxReplicas: 1
secrets:
  POSTGRES_URL: postgres://dev:dev@appointment-postgres-postgresql:5432/dev
  KAFKA_BROKERS: kafka:9092
