image: mrcaidev/telemedicine-appointment
port: 3000
livenessProbe: /livez
readinessProbe: /readyz
paths:
  - /appointments
  - /doctor-availabilities
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
