apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: traefik
          ports:
            - containerPort: 80
            - containerPort: 8080
          volumeMounts:
            - name: traefik-volume-config-map
              mountPath: /etc/traefik
              readOnly: true
          resources:
            requests:
              cpu: 128m
              memory: 256Mi
            limits:
              cpu: 256m
              memory: 512Mi
      volumes:
        - name: traefik-volume-config-map
          configMap:
            name: traefik-config-map
      serviceAccountName: traefik-account
