image: mrcaidev/telemedicine-user
port: 3000
livenessProbe: /livez
readinessProbe: /readyz
paths:
  - /auth
  - /oauth
  - /otp
  - /patients
  - /doctors
  - /clinic-admins
  - /platform-admins
  - /clinics
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
