image: mrcaidev/telemedicine-user
host: localhost
port: 3000
livenessProbe: /livez
readinessProbe: /readyz
paths:
  - /auth
  - /oauth
  - /otp
  - /patients
  - /doctors
  - /clinic-admins
  - /platform-admins
  - /clinics
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
minReplicas: 1
maxReplicas: 1
kafkaCertsNeeded: false
secrets:
  JWT_SECRET: a-string-secret-at-least-256-bits-long
  SUPER_ADMIN_TOKEN: i-am-a-super-admin
  GOOGLE_OAUTH_CLIENT_IDS: 234782665622-nchrj8b3tl88ngd15i371huiei5tne6k.apps.googleusercontent.com,234782665622-4n06echhmlaaniba6up6mp7t0nbup9iv.apps.googleusercontent.com,234782665622-ml21883i8km05ls3t6eschrapvqb6rge.apps.googleusercontent.com
  POSTGRES_URL: postgres://dev:dev@user-postgres-postgresql:5432/dev
  KAFKA_BROKERS: kafka:9092
