apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-all@kubernetescrd
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          {{- range .Values.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: {{ $.Values.port }}
          {{- end }}
