services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - POSTGRES_URL=postgres://test:test@postgres:5432/test
      - KAFKA_BROKERS=kafka:9092
    volumes:
      - .:/code
      - /code/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully

  postgres:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=test
      - POSTGRESQL_PASSWORD=test
      - POSTGRESQL_DATABASE=test
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U test -d test
      interval: 30s
      timeout: 10s
      start_period: 30s
      start_interval: 5s

  init-kafka:
    image: bitnami/kafka
    init: true
    command: sh -c /init/init.sh
    volumes:
      - ./init/kafka:/init
    depends_on:
      kafka:
        condition: service_healthy

  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka:9092 --list
      interval: 30s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
