services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - POSTGRES_URL=postgres://dev:dev@postgres:5432/dev
      - KAFKA_BROKERS=kafka:9092
    volumes:
      - .:/code
      - /code/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully
    restart: always

  postgres:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=dev
      - POSTGRESQL_DATABASE=dev
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
      - postgres-data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dev", "-d", "dev" ]
      interval: 30s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
    restart: always

  init-kafka:
    image: bitnami/kafka
    init: true
    command: [ "bash", "-c", "/init/init.sh" ]
    volumes:
      - ./init/kafka:/init
    depends_on:
      kafka:
        condition: service_healthy

  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=BROKER://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
    volumes:
      - kafka-data:/bitnami/kafka
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list" ]
      interval: 30s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
    restart: always

volumes:
  postgres-data:
  kafka-data:
