kafka-topics.sh --bootstrap-server kafka:9092 --create --topic PatientCreated
kafka-topics.sh --bootstrap-server kafka:9092 --create --topic PatientUpdated
kafka-topics.sh --bootstrap-server kafka:9092 --create --topic PatientDeleted
kafka-topics.sh --bootstrap-server kafka:9092 --create --topic DoctorCreated
kafka-topics.sh --bootstrap-server kafka:9092 --create --topic DoctorUpdated
kafka-topics.sh --bootstrap-server kafka:9092 --create --topic DoctorDeleted
kafka-topics.sh --bootstrap-server kafka:9092 --create --topic AppointmentBooked
kafka-topics.sh --bootstrap-server kafka:9092 --create --topic AppointmentRescheduled
kafka-topics.sh --bootstrap-server kafka:9092 --create --topic AppointmentCancelled
kafka-topics.sh --bootstrap-server kafka:9092 --create --topic EmailRequested
