version: '3.8'

services:
  smart-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - AGENT_ACCESS_KEY=${OPENAI_API_KEY}
      - DIFY_API_KEY=${DIFY_API_KEY}
      - MONGO_URL=mongodb://mongo:27017/
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - redis
      - mongo
    restart: always

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data: