services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=a-string-secret-at-least-256-bits-long
      - SUPER_ADMIN_TOKEN=i-am-a-super-admin
      - POSTGRES_URL=postgres://dev:dev@postgres:5432/dev
      - KAFKA_BROKERS=kafka:9092
      - GOOGLE_OAUTH_CLIENT_IDS=234782665622-nchrj8b3tl88ngd15i371huiei5tne6k.apps.googleusercontent.com,234782665622-4n06echhmlaaniba6up6mp7t0nbup9iv.apps.googleusercontent.com,234782665622-ml21883i8km05ls3t6eschrapvqb6rge.apps.googleusercontent.com
    volumes:
      - .:/code
      - /code/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully
    restart: always

  postgres:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=dev
      - POSTGRESQL_DATABASE=dev
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
      - postgres-data:/bitnami/postgresql
    healthcheck:
      test: pg_isready -U dev -d dev
      interval: 30s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
    restart: always

  init-kafka:
    image: bitnami/kafka
    init: true
    command: sh /init/init.sh
    volumes:
      - ./init/kafka:/init
    depends_on:
      kafka:
        condition: service_healthy

  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
    volumes:
      - kafka-data:/bitnami/kafka
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka:9092 --list
      interval: 30s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
    restart: always

volumes:
  postgres-data:
  kafka-data:
