on:
  push:
    branches:
      - main
    paths:
      - auth/**
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:auth"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/telemedicine-auth:$(echo $GITHUB_SHA | head -c7)

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Connect to kubernetes
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ vars.K8S_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        run: helm upgrade --install auth $GITHUB_WORKSPACE/auth --values $GITHUB_WORKSPACE/auth/values-staging.yaml --set image.repository=${{ vars.DOCKERHUB_USERNAME }}/telemedicine-auth --set image.tag=$(echo $GITHUB_SHA | head -c7)
