on:
  pull_request:
    branches:
      - main
    paths:
      - auth/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check code
        run: bun run check

      - name: Build
        run: bun run build

      - name: Run unit tests
        run: bun run test:unit
