name: Auth Gateway CI

on:
  pull_request:
    branches:
      - main
    paths:
      - auth-gateway/**

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth-gateway
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check code
        run: bun run check

      - name: Run tests
        run: |
          export JWT_SECRET=a-string-secret-at-least-256-bits-long
          bun test --coverage
