name: Notification CI

on:
  pull_request:
    branches:
      - main
    paths:
      - notification/**

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: notification
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check code
        run: bun run check

      - name: Run unit tests
        run: bun run unit-test --coverage

      - name: Run integration tests
        run: |
          docker compose -f docker-compose.test.yaml up -d --build
          docker exec notification-api-1 bun run integration-test --coverage
          docker compose -f docker-compose.test.yaml down -v
