name: Smart Assistant CD

on:
  push:
    branches:
      - main
    paths:
      - smart-assistant/**
  release:
    types:
      - published

permissions:
  contents: read
  deployments: write

jobs:
  set-env:
    name: Set environment variables
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      tag: ${{ steps.set-env.outputs.tag }}
    steps:
      - name: Set environment variables
        id: set-env
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "environment=production" >> "${{ github.output }}"
            echo "tag=${{ github.ref }}" >> "${{ github.output }}"
          else
            echo "environment=staging" >> "${{ github.output }}"
            echo "tag=${{ github.sha }}" >> "${{ github.output }}"
          fi

  build-push:
    name: Build and push image
    needs: set-env
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:smart-assistant"
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/telemedicine-smart-assistant:latest
            ${{ vars.DOCKERHUB_USERNAME }}/telemedicine-smart-assistant:${{ needs.set-env.outputs.tag }}
