name: Smart Assistant CD

on:
  push:
    branches:
      - main
    paths:
      - smart-assistant/**
  release:
    types:
      - published

permissions:
  contents: read
  deployments: write

jobs:
  set-env:
    name: Set environment variables
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      tag: ${{ steps.set-env.outputs.tag }}
    steps:
      - name: Set environment variables
        id: set-env
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "environment=production" >> "${{ github.output }}"
            echo "tag=${{ github.ref }}" >> "${{ github.output }}"
          else
            echo "environment=staging" >> "${{ github.output }}"
            echo "tag=${{ github.sha }}" >> "${{ github.output }}"
          fi

  build-push:
    name: Build and push image
    needs: set-env
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:smart-assistant"
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/telemedicine-smart-assistant:latest
            ${{ vars.DOCKERHUB_USERNAME }}/telemedicine-smart-assistant:${{ needs.set-env.outputs.tag }}

  deploy:
    name: Deploy
    needs:
      - set-env
      - build-push
    if: vars.DEPLOYMENT_ENABLED == 'true'
    runs-on: ubuntu-latest
    environment: ${{ needs.set-env.outputs.environment }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Connect to Kubernetes
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ vars.K8S_CLUSTER_NAME }}

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install smart-assistant ${{ github.workspace }}/deployment/smart-assistant \
            --values ${{ github.workspace }}/deployment/smart-assistant/values.yaml \
            --values ${{ github.workspace }}/deployment/smart-assistant/values-${{ needs.set-env.outputs.environment }}.yaml \
            --set image=${{ vars.DOCKERHUB_USERNAME }}/telemedicine-smart-assistant:${{ needs.set-env.outputs.tag }} \
            --set secrets.AGENT_ENDPOINT=${{ secrets.AGENT_ENDPOINT }} \
            --set secrets.AGENT_ACCESS_KEY=${{ secrets.AGENT_ACCESS_KEY }} \
            --set secrets.MONGO_URL=${{ secrets.SMART_ASSISTANT_MONGO_URL }} \
            --set secrets.REDIS_URL=${{ secrets.SMART_ASSISTANT_REDIS_URL }}
